server:
  port: 8888

spring:
  application:
    name: take-out-config
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/take-out-config.git
          search-paths: config-repo
          default-label: main
          timeout: 5
          username: ${GIT_USERNAME:}
          password: ${GIT_PASSWORD:}
      label: main

# 注册到Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 