server:
  port: 8084

spring:
  application:
    name: take-out-order-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/take_out_system?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 751001ljh
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Redis配置
  data:
    redis:
      host: localhost
      port: 16380

# 注册到Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml 